# https配置
# http.port=80
# server.port=443
# server.ssl.enabled=true
# server.ssl.protocol=TLS
# server.ssl.key-store=classpath:tomcat.keystore
# server.ssl.key-password=123456
# server.ssl.key-store-typ=JKS
# server.ssl.key-alias=tomcat
# jta-atomikos配置
# spring.jta.atomikos.properties.default-jta-timeout=600000
# spring.jta.atomikos.properties.max-timeout=600000
server:
    port: 9001
logging:
    level:
        com.baomidou.mybatisplus.samples.pagination: debug
spring:
    application:
        name: zzyc.scene_base
    aop:
        auto: true
    profiles:
        active: dev
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 1000MB
mybatis-plus:
    mapper-locations: classpath:mapper/*/*/*Mapper.xml
    type-aliases-package: com.zzyc.scene_base.*.*.entity.*
    type-handlers-package: com.zzyc.scene_base.config.handler.*
system:
    config:
        timeZone: Asia/Shanghai
        # Redis失效时间30分钟，单位:分钟
        redisInvalidMinute: 30
        showImgUrl: /fileResource/showImg
